<?php

namespace Blog\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementRepository extends EntityRepository
{

}
