<?php

namespace Blog\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCommentsByAdvert($id)
    {
        $qb = $this->getEntityManager()->createQuery(
            'SELECT c
            FROM BlogNewsBundle:Comment c
            WHERE c.category = :advert_id
            '
        )->setParameter('advert_id', $id);

        return $qb->getResult();
    }
}
